CREATE USER buttbook identified by '12345';
DROP TABLE USUARIOS;
DROP TABLE CONTENIDO;
DROP DATABASE buttbook;

CREATE DATABASE buttbook;
USE buttbook;
CREATE TABLE USUARIOS(IDUSER INT NOT NULL AUTO_INCREMENT, USUARIO VARCHAR(20) NOT NULL, NOMBRE VARCHAR(25) NOT NULL, PASS VARCHAR(80) NOT NULL, PRIMARY KEY(IDUSER));

CREATE TABLE CONTENT(IDUSER INT NOT NULL, NUM INT NOT NULL AUTO_INCREMENT, MESSAGE VARCHAR(250) NOT NULL, FOREIGN KEY (IDUSER) REFERENCES USUARIOS(IDUSER), PRIMARY KEY(NUM));

CREATE TABLE USER_CONTENT(IDUSER INT NOT NULL, HEADER VARCHAR(100) NOT NULL, PROFILEPIC VARCHAR(100) NOT NULL, FOREIGN KEY(IDUSER) REFERENCES USUARIOS(IDUSER));

INSERT INTO USUARIOS(USUARIO, NOMBRE, PASS) VALUES('Prueba', 'Prueba', '12345');

INSERT INTO USER_CONTENT VALUE(1, 'bg/default-header.jpg', 'acc/prueba.jpg');

INSERT INTO CONTENT(IDUSER, MESSAGE) VALUES(1, 'Mensaje de prueba 1');
INSERT INTO CONTENT(IDUSER, MESSAGE) VALUES(1, 'Mensaje de prueba 2');
INSERT INTO CONTENT(IDUSER, MESSAGE) VALUES(1, 'Mensaje de prueba 3');
INSERT INTO CONTENT(IDUSER, MESSAGE) VALUES(1, 'Mensaje de prueba 4');
INSERT INTO CONTENT(IDUSER, MESSAGE) VALUES(1, 'Mensaje de prueba 5');
INSERT INTO CONTENT(IDUSER, MESSAGE) VALUES(1, 'Mensaje de prueba 6');


